{% set name = "fastapi-admin" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastapi-admin-{{ version }}.tar.gz
  sha256: d45cb23a23fc2bbffb0e8adfb1362350a1fe808f47912253c1f067f7d7745d88

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.7
    - babel 
    - aiofiles 
    - aioredis 
    - bcrypt 
    - fastapi 
    - jinja2 
    - python-multipart 
    - tortoise-orm 
    - uvicorn 
    - pendulum 

test:
  imports:
    - fastapi_admin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fastapi-admin/fastapi-admin
  summary: A fast admin dashboard based on FastAPI and TortoiseORM with tabler ui, inspired by Django admin.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sumanth-manchala
